[package]
name = "mapf-visu"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gtk = { version = "0.7.1", package = "gtk4", features = ["v4_8"] }
ndarray = "0.15.6"
wait-timeout = "0.2.0"
